### PR TITLE
Show friendly error message when non-hex deps are found.

### LINKED ISSUE #343: Handle non_hex_deps exception
Trying to publish a package of an app with a non-hex dep rightly fails but the error isn't properly handled so you'll get the message to rerun with `DIAGNOSTIC=1` and then something like:

```
===> Unknown error: {create_package,
                        {error,{non_hex_deps,["eqwalizer_support"]}}}
```

### PR DESCRIPTION
**Pull request by starbelly**
Closes #343

### CODE REVIEW

File: src/rebar3_hex_build.erl [hunk 1]
```diff
@@ -194,6 +194,11 @@ format_error({build_package, Error}) when is_list(Error) ->
 format_error({build_package, {error, Error}}) when is_list(Error) ->
     io_lib:format("Error building package : ~ts", [Error]);
 
+format_error({build_package,{error,{non_hex_deps,Deps}}}) ->
+    DepsStr = lists:join(",", Deps),
+    Error = "Dependencies excluded from the package (only Hex packages can be dependencies) : ~s",
```
Comment (paulo-ferraz-oliveira) [inline src/rebar3_hex_build.erl]:
```suggestion
    Error = "Some dependencies were excluded from the package; only Hex packages can be dependencies: ~s",
```

**Review by paulo-ferraz-oliveira — APPROVED** [review]
